In [1]:
print("hello world")

hello world


In [2]:
print('hlw')

hlw


In [1]:
a=5.0
b=4
print(a.type)
print(b.type)

AttributeError: 'float' object has no attribute 'type'

In [2]:
a=5.0
b=4
print(type(a))
print(type(b))

<class 'float'>
<class 'int'>


In [3]:
%wohos


UsageError: Line magic function `%wohos` not found.


In [4]:
%whos

Variable   Type     Data/Info
-----------------------------
a          float    5.0
b          int      4


In [5]:
del a

In [6]:
%whos


Variable   Type    Data/Info
----------------------------
b          int     4


In [7]:
del b


In [8]:
x=2+3j
print(type(x))

<class 'complex'>


In [9]:
print(x.real)

2.0


In [10]:
print(x.imag)

3.0


In [11]:
del x


In [12]:
a="hi"
print(a.toupper)

AttributeError: 'str' object has no attribute 'toupper'

In [13]:
print(a.upper)

<built-in method upper of str object at 0x102c5b230>


In [14]:
print(a)

hi


In [15]:
%whos


Variable   Type    Data/Info
----------------------------
a          str     hi


In [16]:
del x


NameError: name 'x' is not defined

In [17]:
del a


In [18]:
a=5
b=4.5
print(type(a))
print(type(b))

<class 'int'>
<class 'float'>


In [19]:
c=a+b

In [20]:
print(c)

9.5


In [21]:
b=4.0
print(c)

9.5


In [22]:
%whois


UsageError: Line magic function `%whois` not found.


In [23]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      5
b          float    4.0
c          float    9.5


In [24]:
del a,b,c

In [25]:
%whois


UsageError: Line magic function `%whois` not found.


In [26]:
%whos

Interactive namespace is empty.


In [27]:
False and False or True

True

In [28]:
False or False and True

False

In [29]:
False or True and True

True

In [30]:
True and False or False

False

In [31]:
False and False and True

False

In [32]:
False and False or True

True

In [33]:
not(True)

False

In [34]:
not(False)

True

In [35]:
not(2=3)

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (2796358050.py, line 1)

In [36]:
not(2!=3)

False

In [37]:
pow(3,2,2)

1

In [38]:
pow(3,2)

9

In [39]:
pow(3,2,1)

0

In [40]:
9%1


0

In [41]:
9%2

1

In [1]:
%whos


Interactive namespace is empty.


In [2]:
a=float(input(enter a number))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1888158990.py, line 1)

In [3]:
a=float(input("enter a number"))

enter a number4


In [4]:
print(type(a))

<class 'float'>


In [5]:
%whos

Variable   Type     Data/Info
-----------------------------
a          float    4.0


In [6]:
b=int(input("enter a number"))

enter a number4.7


ValueError: invalid literal for int() with base 10: '4.7'

In [7]:
del a


In [11]:
a =input("enter a number ")
b=input("enter another number ")
if(a>b):
    print("a is the king")
elif(b>a):
    print("b is king")
else:    
    print("atleast we get something")   

enter a number 5
enter another number 10
a is the king


In [13]:
a=int(input("enter a number"))
if a>5:
    print("a is greater")
elif a<5:
    print("a is smaller")
else:
    print("they are both equal to ten")

enter a number5
they are both equal to ten


In [14]:
%whos


Variable   Type    Data/Info
----------------------------
a          int     5
b          str     10


In [15]:
del a
del b

In [26]:
a=float(input("enter a floating number"))


if(b>0):
    print(int(a))
    b=int(a)
    if((b%2==0)):
     print("even")
    else:
     print("odd")
else:
    print("enter a positive no")


enter a floating number-43494
enter a positive no


In [30]:
n=int(input())
i=1
while i<n:
    print(i)
    i+=1
print("finish")    
    

1
finish


In [2]:
def me():
    
print("me")
print("weoh")


IndentationError: expected an indented block after function definition on line 1 (406382770.py, line 2)

In [3]:
def me():
    print("me")
    print("please")
    

In [4]:
3-4


-1

In [5]:
me()

me
please


In [6]:
pr

NameError: name 'pr' is not defined

In [7]:
me?


In [9]:
len??

In [10]:
5-4


1

In [11]:
print(me)

<function me at 0x103956710>


In [12]:
whos?


In [5]:
def r():
    a=10
    b=20
    return a


In [6]:
print(r)

<function r at 0x1054b2320>


In [7]:
def r():
    a=10
    b=20
    return a,b

In [9]:
x,y=r()
print(x,y)

10 20


In [13]:
def add(a,b):
    sums=a+b
    return sums

In [17]:
 d=add(3,4)
print(d)

7


In [18]:
weaddbro=5

In [21]:
def h():
    weaddbro=69
    print(weaddbro)

In [22]:
h()

69


In [23]:
print(weaddbro)

5


In [32]:
def adder(*args):
    a=0
    for i in range(len(args)):
        a+=args[i]
    return a
    
    

In [37]:
print(adder(3,5,8.45,4343))

4359.45


In [44]:
def funk(**apt):
    for i in apt:
        print("var is" ,i ,"and value is" ,apt[i] )
        

In [45]:
print(funk(a=3,b=4))

var is a and value is 3
var is b and value is 4
None


In [20]:
s='Python is a very good language'
p='and is a hell of all'


In [8]:
print(s+p)

Python is a very good language	 and is a hell of all


In [9]:
print(type(s))

<class 'str'>


In [10]:
type(p)

str

In [24]:
value=1450
print(s+p+" with market value of :"+str(value))

Python is a very good languageand is a hell of all with market value of :1450


In [27]:
type(s[6])

str

In [29]:
print(s[6])

In [30]:
s[7:21]

'is a very good'

In [35]:
s[-21:-1]

' a very good languag'

In [36]:
print(len(s))

30


In [38]:
s.strip()

'Python is a very good language'

In [39]:
b='     vkjklsd knfskk.          '

In [40]:
b.strip()


'vkjklsd knfskk.'

In [42]:
%whos

Variable   Type    Data/Info
----------------------------
b          str          vkjklsd knfskk.          
p          str     and is a hell of all
s          str     Python is a very good language
value      int     1450


In [43]:
del b,p,s,value

In [44]:
%whos

Interactive namespace is empty.


In [45]:
a='hfdfhdj'

In [47]:
print(a.capitalize())

Hfdfhdj


In [49]:
capitalize()?

SyntaxError: invalid syntax (1693629859.py, line 1)

In [54]:
l=[1,34,6,'bro',34]
s={1,34,6,'bro',34}
d={23:'twenty three',45:'forty five',45:'forty five'}
t=(1,34,6,'bro',1)

In [52]:
print(type(l))
print(type(d))
print(type(s))
print(type(t))

<class 'list'>
<class 'dict'>
<class 'set'>
<class 'tuple'>


In [55]:
s
l
d
t

(1, 34, 6, 'bro', 1)

In [56]:
s

{1, 34, 6, 'bro'}

In [57]:
l

[1, 34, 6, 'bro', 34]

In [58]:
d

{23: 'twenty three', 45: 'forty five'}

In [59]:
34 in s

True

In [60]:
35 in s

False

In [62]:
t[1:3]

(34, 6)

In [63]:
l[:]

[1, 34, 6, 'bro', 34]

In [64]:
l[::-1]

[34, 'bro', 6, 34, 1]

In [65]:
l[:-1]

[1, 34, 6, 'bro']

In [66]:
l[-1:]

[34]

In [67]:
l.add(2)

AttributeError: 'list' object has no attribute 'add'

In [68]:
l.append(2)

In [69]:
l


[1, 34, 6, 'bro', 34, 2]

In [70]:
l.append(2:)

SyntaxError: invalid syntax (4120753259.py, line 1)

In [71]:
l.remove(2)

In [72]:
l

[1, 34, 6, 'bro', 34]

In [73]:
l.pop(1)

34

In [74]:
t.count

<function tuple.count(value, /)>

In [75]:
t.count(1)

2

In [76]:
t.count(2)

0

In [77]:
l3=l


In [78]:
l3

[1, 6, 'bro', 34]

In [79]:
l3[3]=4


In [80]:
l3


[1, 6, 'bro', 4]

In [81]:
l

[1, 6, 'bro', 4]

In [82]:
t[2]=3


TypeError: 'tuple' object does not support item assignment

In [83]:
l.extend?

In [84]:
l.extend


<function list.extend(iterable, /)>

In [85]:
l.extend(3,5,7
        )

TypeError: list.extend() takes exactly one argument (3 given)

In [86]:
l.extend(2)

TypeError: 'int' object is not iterable

In [87]:
l.extend?


In [88]:
help(l.extend)

Help on built-in function extend:

extend(iterable, /) method of builtins.list instance
    Extend list by appending elements from the iterable.



In [89]:
l.extend

<function list.extend(iterable, /)>

In [90]:
l

[1, 6, 'bro', 4]

In [91]:
l.extend(str)

TypeError: 'type' object is not iterable

In [92]:
l.extend(s)

In [93]:
l

[1, 6, 'bro', 4, 1, 34, 'bro', 6]

In [94]:
l.avg()

AttributeError: 'list' object has no attribute 'avg'

In [95]:
l.sort


<function list.sort(*, key=None, reverse=False)>

In [96]:
l.sort(asc)

NameError: name 'asc' is not defined

In [97]:
l.sort?


In [98]:
l.sort(key=asc)

NameError: name 'asc' is not defined

In [101]:
l.sort(reverse=True)

TypeError: '<' not supported between instances of 'str' and 'int'

In [100]:
l.sort?

In [103]:
l.sort(key=None ,reverse=True)

TypeError: '<' not supported between instances of 'str' and 'int'

In [104]:
l

[1, 6, 'bro', 4, 1, 34, 'bro', 6]

In [108]:
v=int(l)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [107]:
v.sort(key=None,reverse=True)

AttributeError: 'str' object has no attribute 'sort'

In [109]:
l.sort

<function list.sort(*, key=None, reverse=False)>

In [111]:
help(l.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Sort the list in ascending order and return None.
    
    The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
    order of two equal elements is maintained).
    
    If a key function is given, apply it once to each list item and sort them,
    ascending or descending, according to their function values.
    
    The reverse flag can be set to sort in descending order.



In [1]:
import numpy as np



In [7]:
b=np.array([[1,2,3,4,5],[3,5,4,6,9]])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.dtype

dtype('int64')

In [5]:
b.all

<function ndarray.all>

In [10]:
b.ndim

2

In [11]:
b[0,3]

4

In [12]:
b.shape

(2, 5)

In [14]:
shape(2)

NameError: name 'shape' is not defined

In [15]:
b.size

10

In [16]:
b.shape[1]

5

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(20,40,4)

array([20, 24, 28, 32, 36])

In [20]:
np.random.bit_generator

<module 'numpy.random.bit_generator' from '/Users/prasiddha/anaconda3/lib/python3.10/site-packages/numpy/random/bit_generator.cpython-310-darwin.so'>

In [23]:
np.random.permutation(np.arange(20))

array([ 2, 11,  6, 18, 14,  7,  4, 13,  1,  9, 19,  5, 10, 17,  3, 12,  8,
        0, 15, 16])

In [25]:
np.random.permutation(20)

array([16, 15, 13,  1,  5,  0, 14, 11, 10,  3,  2, 17,  8,  6, 18,  4,  9,
       12, 19,  7])

In [27]:
np.reshape(20,4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [45]:
a=np.arange(90).reshape(3,30)

In [46]:
a.shape

(3, 30)

In [32]:
c=np.random.rand(1000)

In [42]:
a.reshape?

In [47]:
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
  54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
  84 85 86 87 88 89]]


In [48]:
a=a+5


In [49]:
print(a)

[[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
  29 30 31 32 33 34]
 [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
  59 60 61 62 63 64]
 [65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88
  89 90 91 92 93 94]]


In [51]:
np.hstack


<function numpy.hstack(tup)>

In [54]:
a=np.random.rand(12)


In [55]:
print(a)

[0.18101602 0.67621489 0.89704084 0.35381857 0.7801261  0.01769681
 0.52727208 0.93575209 0.99449775 0.77049956 0.04900742 0.8254921 ]


In [56]:
b=np.random.rand(12)

In [57]:
print(b)

[0.63014784 0.62710093 0.06873589 0.12115276 0.7020109  0.16159723
 0.36181135 0.79958523 0.22109161 0.26456623 0.01352164 0.46790999]


In [58]:
x=np.hstack((a,b))

In [59]:
print(x)

[0.18101602 0.67621489 0.89704084 0.35381857 0.7801261  0.01769681
 0.52727208 0.93575209 0.99449775 0.77049956 0.04900742 0.8254921
 0.63014784 0.62710093 0.06873589 0.12115276 0.7020109  0.16159723
 0.36181135 0.79958523 0.22109161 0.26456623 0.01352164 0.46790999]
